Repository ursjoss/scipamato, pull requests merged in 2019-09, with the labels that each got.

#123 Chore/improve GitHub workflows
  .github/workflows/check.yml
  .github/workflows/sonar.yml
Labels: chore

#128 [127] - Core: Remove LoadingBehavior for most usages
  CHANGELOG.asciidoc
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/code/CodeEditPage.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/code/CodeEditPage_de.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/code/CodeListPage.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/code/CodeListPage.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/code/CodeListPage_de.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/codeclass/CodeClassEditPage.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/codeclass/CodeClassEditPage_de.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/common/DefinitionEditHeaderPanel.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/keyword/KeywordEditPage.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/keyword/KeywordEditPage_de.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/keyword/KeywordListPage.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/keyword/KeywordListPage.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/keyword/KeywordListPage_de.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/newsletter/edit/NewsletterEditPage.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/newsletter/edit/NewsletterEditPage.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/newsletter/edit/NewsletterEditPage_de.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/newsletter/list/NewsletterListPage.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/newsletter/list/NewsletterListPage.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/newsletter/list/NewsletterListPage_de.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/newsletter/topic/NewsletterTopicEditPage.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/newsletter/topic/NewsletterTopicEditPage_de.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/newsletter/topic/NewsletterTopicListPage.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/newsletter/topic/NewsletterTopicListPage.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/newsletter/topic/NewsletterTopicListPage_de.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel_de.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/paper/list/PaperListPage.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/paper/list/PaperListPage.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/paper/list/PaperListPage_de.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/user/UserEditPage.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/user/UserEditPage.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/user/UserEditPage_de.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/user/UserListPage.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/user/UserListPage.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/user/UserListPage_de.properties
Labels: bug

#126 [118] - Export search result in RIS format - Spike
  CHANGELOG.asciidoc
  implementation/scipamato/common/persistence-api/src/main/java/ch/difty/scipamato/common/config/ApplicationProperties.java
  implementation/scipamato/common/utils/src/main/kotlin/ch/difty/scipamato/common/Utils.kt
  implementation/scipamato/common/utils/src/test/kotlin/ch/difty/scipamato/common/UtilsTest.kt
  implementation/scipamato/common/wicket/src/main/java/ch/difty/scipamato/common/config/AbstractScipamatoProperties.java
  implementation/scipamato/common/wicket/src/main/java/ch/difty/scipamato/common/config/ScipamatoBaseProperties.java
  implementation/scipamato/common/wicket/src/test/kotlin/ch/difty/scipamato/common/config/AbstractScipamatoPropertiesTest.kt
  implementation/scipamato/common/wicket/src/test/kotlin/ch/difty/scipamato/common/web/TestCoponents.kt
  implementation/scipamato/core/logic/src/main/kotlin/ch/difty/scipamato/core/logic/parsing/AuthorParserStrategies.kt
  implementation/scipamato/core/logic/src/test/kotlin/ch/difty/scipamato/core/logic/parsing/AuthorParserStrategyTest.kt
  implementation/scipamato/core/persistence-jooq/src/intTest/kotlin/ch/difty/scipamato/core/persistence/TestApplication.kt
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/config/ApplicationCoreProperties.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/config/ScipamatoCoreProperties.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/config/ScipamatoProperties.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/logic/exporting/RisAdapter.kt
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/logic/exporting/RisExporterConfiguration.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/logic/exporting/RisExporterStrategy.kt
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/behavior/AjaxDownload.kt
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/paper/result/ResultPanel.html
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/paper/result/ResultPanel.java
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/paper/result/ResultPanel.properties
  implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/paper/result/ResultPanel_de.properties
  implementation/scipamato/core/web/src/main/java/com/gmail/gcolaianni5/jris/JRis.kt
  implementation/scipamato/core/web/src/main/java/com/gmail/gcolaianni5/jris/RisRecord.kt
  implementation/scipamato/core/web/src/main/java/com/gmail/gcolaianni5/jris/RisTag.kt
  implementation/scipamato/core/web/src/main/java/com/gmail/gcolaianni5/jris/RisType.kt
  implementation/scipamato/core/web/src/main/resources/application.properties
  implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/config/ScipamatoCorePropertiesTest.java
  implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/config/ScipamatoPropertiesTest.java
  implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/logic/export/DefaultRisAdapterTest.kt
  implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/logic/export/DistillerSrRisAdapterTest.kt
  implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/logic/export/RisAdapterFactoryTest.kt
  implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/logic/export/RisExporterConfigurationTest.java
  implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/logic/export/RisExporterStrategyTest.kt
  implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/logic/export/TestRisExporterConfiguration.java
  implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/web/AbstractWicketTest.java
  implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/web/behavior/AjaxTextDownloadTest.kt
  implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/web/paper/result/ResultPanelTest.java
  implementation/scipamato/public/persistence-api/src/main/java/ch/difty/scipamato/publ/config/ApplicationPublicProperties.java
  implementation/scipamato/public/web/src/main/java/ch/difty/scipamato/publ/config/ScipamatoPublicProperties.java
Labels: enhancement, scipamato-core, spike
